# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_betas <- function(full) {
    .Call('_BootPermLm_get_betas', PACKAGE = 'BootPermLm', full)
}

bootstrap_distribution <- function(indices, full, num_samples) {
    .Call('_BootPermLm_bootstrap_distribution', PACKAGE = 'BootPermLm', indices, full, num_samples)
}

permutation_distribution <- function(indices, full, num_samples) {
    .Call('_BootPermLm_permutation_distribution', PACKAGE = 'BootPermLm', indices, full, num_samples)
}

